config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :users
  resources :attendance, only: [:new, :create]
  root to:'events#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :confirmation_send

  def confirmation_send
    EventMailer.confirmation_email(self).deliver_now
  end

  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :admin, class_name: 'User', dependent: :destroy

=begin 
  validates :start_date,
   presence: true

  
  validate :start_date_cannot_be_in_the_past
  #impossible de créer ou modifier un évènement dans le passé
      def start_date_cannot_be_in_the_past
        if start_date < Date.current
         errors.add(:start_date, "L'évènement doit avoir une date supérieur à la date du jour")
       end
      end    


  validates :duration,
    presence: true,
    #strictement positif
    numericality: {greater_than_or_equal_to: 0}
    #nb minutes doit être un multiple de 5 
  validate :multiple_by_5
      def multiple_by_5
        unless duration.to_i%5 == 0
          errors.add(:duration, "la durée doit être un multiple de 5")
        end
      end

  validates :title,
    presence: true,
    length: {minimum: 5, maximum: 140}

  validates :description,
    presence: true,
    length: {minimum: 20, maximum: 1000}

  validates :price,
    presence: true,
    #doit être compris entre 1 et 1000
    numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 1000}

  validates :location,
    presence: true
=end

end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
  has_many :events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances
  has_many :events, through: :attendances

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]

  around_action :set_time_zone

  def index
    @event = Event.all.sample
    @events = Event.all
    @city = ["https://abylon-conseil.com/wp-content/uploads/2020/03/Smart-city1.png", "https://www.veolia.com/sites/g/files/dvc4206/files/styles/content_push_teaser/public/image/2020/10/Nouvelle%20Orl%C3%A9ans%20GettyImages-CP.jpg?itok=Cg_XCU0A","https://siecledigital.fr/wp-content/uploads/2021/02/1920_20200107-01-011-2-300x230.jpg","https://www.techno-science.net/illustration/Definition/300px/Moscow-City-28-03-2010-2.jpg"]

    @avatar = ["https://cdn-icons-png.flaticon.com/512/206/206853.png","https://cdn-icons-png.flaticon.com/512/3135/3135715.png","https://www.immo-passion-maroc.com/wp-content/uploads/2021/06/people-profile-icon_24877-40756.jpg"]
  end

  def show 
    @event = Event.find(params[:id])

    @city = ["https://abylon-conseil.com/wp-content/uploads/2020/03/Smart-city1.png", "https://www.veolia.com/sites/g/files/dvc4206/files/styles/content_push_teaser/public/image/2020/10/Nouvelle%20Orl%C3%A9ans%20GettyImages-CP.jpg?itok=Cg_XCU0A","https://siecledigital.fr/wp-content/uploads/2021/02/1920_20200107-01-011-2-300x230.jpg","https://www.techno-science.net/illustration/Definition/300px/Moscow-City-28-03-2010-2.jpg"]

  end


  def new
    @event = Event.new
  end

  def create

    @event = Event.new(
      'start_date' => params[:start_date],
      'duration' => params[:duration],
      'title' => params[:title],
      'description' => params[:description],
      'price' => params[:price],
      'location' => params[:location],
      'admin_id' => current_user.id)

    if @event.save
      redirect_to event_path(@event.id)
    else
      render 'new'
    end
  end


  private


  
def set_time_zone(&block)
   Time.use_zone('Europe/Paris', &block)
end

def authenticate_user
  unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_user_session_path
  end
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show, :edit,:update]

  def show
    @user = User.find(params[:id])
    @events = Event.all
    @city = ["https://abylon-conseil.com/wp-content/uploads/2020/03/Smart-city1.png", "https://www.veolia.com/sites/g/files/dvc4206/files/styles/content_push_teaser/public/image/2020/10/Nouvelle%20Orl%C3%A9ans%20GettyImages-CP.jpg?itok=Cg_XCU0A","https://siecledigital.fr/wp-content/uploads/2021/02/1920_20200107-01-011-2-300x230.jpg","https://www.techno-science.net/illustration/Definition/300px/Moscow-City-28-03-2010-2.jpg"]

    @avatar = ["https://cdn-icons-png.flaticon.com/512/206/206853.png","https://cdn-icons-png.flaticon.com/512/3135/3135715.png","https://www.immo-passion-maroc.com/wp-content/uploads/2021/06/people-profile-icon_24877-40756.jpg"]
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    params.require(:user).permit(:first_name,:last_name, :description).inspect
  
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end


  private 

  def user_params
    user_params = params.require(:user).permit(:first_name,:last_name, :description)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_user_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
 
 
 <div class="hero-image">
  <div class="hero-text">
    <h1 style="font-size:5rem"><span style="color:#fe1919; font-weight: 900">Your</span><span style="color:#fec119;font-weight: 700">Event</span></h1>
    <p>Best Events For You !</p>
    <a href="<%=new_event_path%>" class="mt-2 mb-5 col-sm-12 col-md-6 col-lg-6 btn btn-primary pulse rounded-pill p-3" style="border: none;background: linear-gradient(90deg, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 0%, rgba(252,176,69,1) 100%);">Create your Event</a>
    <div><a class="px-3 py-2"style="background-color:none; border:1px solid #fe1919; color:#fe8819; border-radius:15px"href="#main">Découvrir</a></div>
    
  </div>
</div> 


<div id="main"class="row justify-content-center mt-5">

</div>
<h2 class="row justify-content-center mb-5" style="color:#fe1919"> Notre coup de coeur du jour </h2>

<div class="container row justify-content-center">
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <div class="card card-small card-home pulse">
        <div class="thumbnail">           
                <img alt="Opt alp thumbnail" style ="filter: brightness(50%);"src="<%=@city.sample%>">
                <a href="<%=event_path(@event.id)%>">
                    <div class="thumb-cover"></div>
                </a>            
                <div class="details">
                <a href="<%=user_path(@event.admin_id)%>"class="user">
                     <div class="user-photo">
                          <img alt="Thumb" src="<%=@avatar.sample%>">
                     </div>
                     <div class="name"><%=User.find(@event.admin_id).first_name%>  <%=User.find(@event.admin_id).last_name%></div>
                </a> 
            </div>            
        </div>
        <div class="card-info">
            <div class="moving">
                    <h3><%= @event.title%></h3>
                    <p class="p"><%= @event.description%></p>
                    <p>Date : <%=@event.start_date%></p>
                    <a class="btn btn-primary active mt-2 mb-4" href="<%=event_path(@event.id)%>">Détails</a>
                    <br>
            </div>
        </div>
    </div>
</div>



<h2 class="row justify-content-center mb-5" style="color:#fe1919 "> Best Last Events</h2>
<div class="container row justify-content-center">
<% @events.each do |event| %>

<div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <div class="card card-small card-home">
        <div class="thumbnail">           
                <img alt="Opt alp thumbnail" style ="filter: brightness(50%);"src="<%=@city.sample%>">
                <a href="<%=event_path(event.id)%>">
                    <div class="thumb-cover"></div>
                </a>            
                <div class="details">
                <a href="<%=user_path(event.admin_id)%>"class="user">
                     <div class="user-photo">
                          <img alt="Thumb" src="<%=@avatar.sample%>">
                     </div>
                     <div class="name"><%=User.find(event.admin_id).first_name%>  <%=User.find(event.admin_id).last_name%></div>
                </a> 
            </div>            
        </div>
        <div class="card-info">
            <div class="moving">
                    <h3><%= event.title%></h3>
                    <p class="p"><%= event.description%></p>
                    <p>Date : <%=event.start_date%></p>
                    <a class="btn btn-info active mt-2 mb-4" href="<%=event_path(event.id)%>">Détails</a>
                    <br>
            </div>
        </div>
    </div>
</div>

  <% end %>

app/views/events/new.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">

<h1 style="color: white">Créer un Event</h1>

  <% if @event.errors.any? %>
              <% @event.errors.full_messages.each do |message| %>
                    <div class="container alert alert-danger d-flex align-items-center p-1 mt-1" role="alert"><%= message %></div>
                <% end %>
              <% end %>


<%= form_for @event do |f|%>
  <div class="container contact " style="height:80vh">
    <div class="row">
      <div class="col-md-3">

      </div>
      <div class="col-md-9">
        <div class="contact-form">
          <div class="form-group">
            <label class="control-label col-sm-2" for="fname">Titre :</label>
            <div class="col-sm-10">          
            <%= f.text_field :title, class:"form-control area"%>
            </div>
          </div>

          <div class="form-group mt-3">
            <label class="control-label col-sm-4" for="lname">Date :</label>
            <div class="col-sm-10">          
            <%= f.date_field :start_date, class:"form-control area"%>
            </div>
          </div>

          <div class="form-group mt-3">
            <label class="control-label col-sm-3" for="lname">Description :</label>
            <div class="col-sm-10">          
            <%= f.text_area :description, class:"form-control area"%>
            </div>
          </div>

          <div class="form-group mt-3">
            <label class="control-label col-sm-4" for="fname">Durée:(en minutes)</label>
            <div class="col-sm-10">          
            <%= f.text_field :duration, class:"form-control area"%>
            </div>
          </div>

          <div class="form-group mt-3">
            <label class="control-label col-sm-2" for="fname">Tarif :</label>
            <div class="col-sm-10">          
            <%= f.text_field :price, class:"form-control area"%>
            </div>
          </div>

          <div class="form-group mt-3">
            <label class="control-label col-sm-3" for="fname">Localisation :</label>
            <div class="col-sm-10">          
            <%= f.text_field :location, class:"form-control area"%>
            </div>
          </div>
          
          <div class="form-group mt-3">        
            <div class="col-sm-offset-2 col-sm-10 mt-3">
            <%= submit_tag "Créer l'Event", class: 'btn btn-primary rounded-pill' %>

            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <a href="<%= root_path %>" class="btn btn-primary m-3 rounded-pill mt-4">👈 Revenir au menu</a>
  </div>



<% end %>

app/views/events/show.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">


<div class="container mt-5">

    <h3 class="m-3">Events organisé :</h3>
    <hr>
<div class="row">
    <div class="col-md-6 col-s-12">
        <div class="card card-small">
            <div class="thumbnail">           
                <img alt="Opt alp thumbnail" style ="filter: brightness(50%);"src="<%=@city.sample%>">                 
            </div>
            <div class="card-info">
                <div class="moving">
                    <h3><%= @event.title%></h3>
                    <p>Localisation : <%= @event.location%></p>
                    <p>Prix : <%=@event.price%></p>
                    <a href="<%= root_path %>" style="color:#fe19eb" class="btn btn-Danger m-3 rounded-pill">S'inscrire</a>

                    <br>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-s-12">
        <div class="card card-small p-2">
                    <p style="text-decoration:underline">Description :</p>
                    <p class="p"><%= @event.description%></p>
                    <br>
                    <p style="text-decoration:underline">Date :</p>
                    <p class="p"><%= @event.start_date%></p>
                    <br>
                    <p style="text-decoration:underline">Durée :</p>
                    <p class="p"><%= @event.duration%>  minutes</p>
                    
        </div>
    </div>
</div>


            <a href="<%= root_path %>" class="btn btn-primary m-3 rounded-pill">👈 Revenir aux Event</a>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--BOOSTRAP CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--BOOSTRAP JAVASCRIPT-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></script>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>

    <div class="container">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="<%= root_path %>" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <span class="fs-4" style="color:#fe1919; font-weight: 900">Your</span><span class="fs-4" style="color:#fec119;font-weight: 700">Event</span>
        </a>

        <ul class="nav nav-pills">
          <li class="nav-item"><a href="<%= root_path %>" class="nav-link" >Home</a></li>
          <li class="nav-item"><a href="<%=new_event_path%>" class="nav-link">Créer un event</a></li>

          <% if current_user%>
           <li class="nav-item">
            <div class="dropdown show">
              <a class="btn btn-secondary dropdown-toggle active py-2" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mon Profil
              </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="<%=user_path(current_user.id)%>" style="color:#fe1919">Mon Profil</a>
                  <a class="dropdown-item" href="<%=destroy_user_session_path%>" style="color:#fec119">Se déconnecter</a>
                </div>
            </div>
          </li>
          <%else%>
          <li class="nav-item">
            <div class="dropdown show">
              <a class="btn btn-secondary dropdown-toggle active py-2" href="<%=new_user_session_path%>" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Connexion
              </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="<%=new_user_registration_path%>" style="color:#fe4219 ">S'inscrire</a>
                <a class="dropdown-item" href="<%= new_user_session_path%>" style="color:#fe4219">Connexion</a>
                </div>
            </div>
          </li>
         <%end%>
        </ul>
      </header>

      <%if notice == "" || alert == ""%>
      <p class="alert alert-success notice"><%= notice %></p>
      <p class="alert alert-danger"><%= alert %></p>
      <%end%>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/edit.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">

<h1 style="color:#fe1919">Editer le profil</h1>




<%= form_for @user do |f|%>
  <div class="container contact " style="height:80vh">
    <div class="row">
      <div class="col-md-3">
        <div class="contact-info">
          <img src="https://image.ibb.co/kUASdV/contact-image.png" alt="image"/>
          <h2>Modifier votre profil</h2>
        </div>
      </div>
      <div class="col-md-9">
        <div class="contact-form">
          <div class="form-group">
            <label class="control-label col-sm-2" for="fname">Prénom :</label>
            <div class="col-sm-10">          
            <%= f.text_field :first_name, class:"form-control area"%>
            </div>
          </div>

          <div class="form-group mt-3">
            <label class="control-label col-sm-4" for="lname">Nom de famille :</label>
            <div class="col-sm-10">          
            <%= f.text_field :last_name, class:"form-control area"%>
            </div>
          </div>

          <div class="form-group mt-3">
            <label class="control-label col-sm-4" for="lname">Description :</label>
            <div class="col-sm-10">          
            <%= f.text_area :description, class:"form-control area"%>
            </div>
          </div>
          
          <div class="form-group">        
            <div class="col-sm-offset-2 col-sm-10 mt-3">
            <%= submit_tag "Modifier", class: 'btn btn-primary rounded-pill' %>

            </div>
          </div>
        </div>
      </div>
    </div>
    <a href="<%= user_path(params[:id]) %>" class="btn btn-primary m-3 rounded-pill mt-4"> Revenir au profil</a>
  </div>

<% end %>

app/views/users/show.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">

<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7">
            <div class="card p-3 py-4">

            <%if current_user.id == params[:id].to_i%>

                <div class="text-center"> <img src="http://img.over-blog-kiwi.com/0/98/03/83/20151017/ob_6b4eb9_tumblr-nqy9pkedgm1s9poh0o1-500.gif" width="100" class="rounded-circle"> </div>
                <%if Event.find_by(admin_id: @user.id)%>
                  <div class="text-center mt-3"> <span class="bg-secondary p-1 px-4 rounded text-white">Fondateur d'Event</span>
                <%else%>
                  <div class="text-center mt-3"> <span class="bg-secondary p-1 px-4 rounded text-white">Participant</span>
                <%end%>

                    <h5 class="mt-2 mb-0"><%= @user.first_name.capitalize%>  <span style="color: #7a7a7a"><%= @user.last_name.upcase%></span></h5>
                    <div class="px-4 mt-1">
                        <p class="fonts" style="font-size:12px"><i><%=@user.description%></i></p>
                    </div>
                    
                    <div class="buttons"> 
                    <a href="<%= edit_user_registration_path %>" class="btn btn-primary m-3  ms-3 rounded-pill">Paramètres</a>
                    <a href="<%= edit_user_path(current_user.id) %>" class="btn btn-primary m-3  ms-3 rounded-pill" style="color:#fe4219;background-color:#FFF">Editer profil</a>
                     </div>
                    
                    <h3 class="m-3">Events organisés :</h3>
                    <%unless Event.find_by(admin_id: @user.id)%>
                        <p><i style="font-size:12px; color:  #b7b7b7  ">Aucun Event créé à ce jour</i></p>      
                    <%end%>
                                                        <hr>
                    <% @events.each do |event| %>
                    <%if event.admin_id == params[:id].to_i%>


                    <div class="col-12">
                        <div class="card card-small card-home">
                            <div class="thumbnail">           
                                    <img alt="Opt alp thumbnail" style ="filter: brightness(50%);"src="<%=@city.sample%>">
                                    <a href="<%=event_path(event.id)%>">
                                        <div class="thumb-cover"></div>
                                    </a>            
                                    
                            </div>
                            <div class="card-info">
                                <div class="moving">
                                        <h3><%= event.title%></h3>
                                        <p class="p"><%= event.description%></p>
                                        <p>Date : <%=event.start_date%></p>
                                        <a class="btn btn-primary active mt-2 mb-4" href="<%=event_path(event.id)%>">Détails</a>
                                        <br>
                                </div>
                            </div>
                        </div>
                    </div>
                    <%end%>
                    <%end%>
                    <%else%>

                        <p><i style="font-size:12px; color:  #b7b7b7  ">Vous n'êtes pas autorisé à voir cette page</i></p>      

                    <%end%>


        <a href="<%= root_path %>" class="btn btn-primary m-3 rounded-pill">👈 Revenir aux Event</a>
                </div>
            </div>
        </div>
    </div>
</div>